--1번


CREATE TABLE TB_CATEGORY(
NAME VARCHAR2(10),
USE_YN CHAR(1) DEFAULT 'Y' NOT NULL
);

INSERT INTO TB_CATEGORY VALUES(NULL,'Y');
SELECT * FROM TB_CATEGORY;
DROP TABLE TB_CATEGORY;

--2번

CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)  
);
SELECT * FROM TB_CLASS_TYPE;