--1번
SELECT STUDENT_NO 학번 ,STUDENT_NAME 이름 ,TO_CHAR(ENTRANCE_DATE,'YYYY/MM/DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO =002
ORDER BY 3;

--2번

SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME)!=3;

--3번

SELECT PROFESSOR_NAME 교수이름,  TO_CHAR(SYSDATE,'YYYY')- (1900+SUBSTR(PROFESSOR_SSN,0,2))
FROM TB_PROFESSOR;

--4번
SELECT  SUBSTR(PROFESSOR_NAME,2,2) 이름
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME)!=2 AND LENGTH(PROFESSOR_NAME)!=4;


--5번

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE TO_CHAR(ENTRANCE_DATE,'YYYY')-(1900+SUBSTR(STUDENT_SSN,1,2)) =19
ORDER BY 1 DESC;

--6번
SELECT TO_CHAR (TO_DATE(20201225),'DAY') 
FROM DUAL;

--7번
SELECT TO_CHAR(TO_DATE(991011,'RR/MM/DD'),'RRRR/MM/DD'),--1999년
TO_CHAR(TO_DATE(491011,'RR/MM/DD'),'RRRR/MM/DD'),--2049
TO_CHAR(TO_DATE(991011,'YY/MM/DD'),'YYYY/MM/DD'),--2099
TO_CHAR(TO_DATE(491011,'YY/MM/DD'),'YYYY/MM/DD')--2049
FROM DUAL;

--8번
SELECT STUDENT_NO , STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) !='A';

--9번
SELECT ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';
--10번
SELECT DEPARTMENT_NO 학과번호 , COUNT(DEPARTMENT_NO) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--11번
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12번 모르겠어요
SELECT  SUBSTR(TERM_NO,1,4),STUDENT_NAME,AVG(POINT)
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE DEPARTMENT_NO='A112113'  
GROUP BY TERM_NO,STUDENT_NAME;
--13번
SELECT DEPARTMENT_NO,COUNT(ABSENCE_YN)
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N'
GROUP BY DEPARTMENT_NO
ORDER BY 1;
--14번
SELECT STUDENT_NAME, COUNT(STUDENT_NAME)
FROM TB_STUDENT
HAVING COUNT(STUDENT_NAME) >1
GROUP BY STUDENT_NAME
ORDER BY 1 ASC; 
--15번 모르겠어요
SELECT  SUBSTR(TERM_NO,1,4),AVG(POINT)
FROM TB_GRADE
WHERE STUDENT_NO='A112113'  
GROUP BY ROLLUP (TERM_NO)
ORDER BY 1;