
--1번
SELECT EMP_ID,EMP_NAME,DEPT_TITLE,JOB_NAME,HIRE_DATE,ROWNUM 순위
FROM (SELECT
EMP_NAME,
(SALARY+SALARY*BONUS)*12,
HIRE_DATE,
JOB_NAME,
DEPT_TITLE,
EMP_ID
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE BONUS IS NOT NULL
ORDER BY (SALARY*BONUS)*12 DESC)
WHERE ROWNUM <=5;



--2번 
SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
HAVING SUM(SALARY) > (  
SELECT SUM(SALARY)*0.2 FROM EMPLOYEE)
GROUP BY DEPT_TITLE;

--3번 
WITH GET_SAL AS(
SELECT SUM(SALARY)"SUM_SALARY",AVG(SALARY) "AVG_SALARY"
FROM EMPLOYEE)
SELECT SUM_SALARY,AVG_SALARY
FROM GET_SAL;


